#!/bin/sh
#Script generated by packit.perl on Sun Feb  7 21:01:22 2016.

if [ -z "$UNPACK_ONLY" -a "`id -u`" != 0 ] ; then
  echo "This script needs to be run with root privileges.  Please try:"
  echo "  sudo -H sh $0"
  exit 1
fi
export HOME="`getent passwd 0 | cut -d: -f6`"
cd "`mktemp -d || echo /dev/null`"
if [ "$?" != 0 ] ; then
  echo "Unable to change to temporary directory; cannot continue."
  exit 2
fi
echo "Working in `pwd`..."
#Add hook to ensure the payload runs after successful unpacking
nexit() {
if [ "$1" = "0" ] ; then
 do_md5_check || { echo "Checksum fail." ; exit 1 ; }
 if [ -n "$UNPACK_ONLY" ] ; then
  echo "Unpack complete in `pwd`. Exiting."
 else
  chmod +x upgrade_to_8.sh
  echo 'Unpack phase complete.  Running upgrade_to_8.sh' ; echo '====>>>'
  exec ./upgrade_to_8.sh <&1
 fi
else \exit "$@"
fi }
alias exit=nexit
#Always prefer Perl for uudecoding
uudecode() {
 if which perl >/dev/null ; then
  read l0 l1 l2
  perl -ne 'print unpack("u*",$_)' >$l2 &&
  chmod $l1 $l2
 else
  uudecode "$@"
 fi
}
#No extra md5sum checking
do_md5_check() {
  true
}
#!/bin/sh
# This is a shell archive (produced by GNU sharutils 4.15.2).
# To extract the files from this archive, save it to some FILE, remove
# everything before the '#!/bin/sh' line above, then type 'sh FILE'.
#
lock_dir=_sh10570
# Made on 2016-02-07 21:01 GMT by <tbooth@bender>.
# Source directory was '/home/tbooth/build/build-bio-linux/upgrade_to_8'.
#
# Existing files WILL be overwritten.
#
# This shar contains:
# length mode       name
# ------ ---------- ------------------------------------------
#   4825 -rwxrwxr-x bl_master_package_list.txt
#   2212 -rwxrwxr-x bl_install_master_list.sh
#   1746 -rw-rw-r-- message1.txt
#   3125 -rw-rw-r-- sources.list.clean
#    725 -rw-rw-r-- pseudo_orphans.txt
#   5490 -rwxrwxr-x pick_cran_mirror.py
#   9578 -rw-rw-r-- bio-linux-keyring.deb
#  13419 -rwxrwxr-x upgrade_to_8.sh
#
MD5SUM=${MD5SUM-md5sum}
f=`${MD5SUM} --version | egrep '^md5sum .*(core|text)utils'`
test -n "${f}" && md5check=true || md5check=false
${md5check} || \
  echo 'Note: not verifying md5sums.  Consider installing GNU coreutils.'
if test "X$1" = "X-c"
then keep_file=''
else keep_file=true
fi
echo=echo
save_IFS="${IFS}"
IFS="${IFS}:"
gettext_dir=
locale_dir=
set_echo=false

for dir in $PATH
do
  if test -f $dir/gettext \
     && ($dir/gettext --version >/dev/null 2>&1)
  then
    case `$dir/gettext --version 2>&1 | sed 1q` in
      *GNU*) gettext_dir=$dir
      set_echo=true
      break ;;
    esac
  fi
done

if ${set_echo}
then
  set_echo=false
  for dir in $PATH
  do
    if test -f $dir/shar \
       && ($dir/shar --print-text-domain-dir >/dev/null 2>&1)
    then
      locale_dir=`$dir/shar --print-text-domain-dir`
      set_echo=true
      break
    fi
  done

  if ${set_echo}
  then
    TEXTDOMAINDIR=$locale_dir
    export TEXTDOMAINDIR
    TEXTDOMAIN=sharutils
    export TEXTDOMAIN
    echo="$gettext_dir/gettext -s"
  fi
fi
IFS="$save_IFS"
if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null
then if (echo -n test; echo 1,2,3) | grep n >/dev/null
     then shar_n= shar_c='
'
     else shar_n=-n shar_c= ; fi
else shar_n= shar_c='\c' ; fi
if test ! -d ${lock_dir} ; then :
else ${echo} "lock directory ${lock_dir} exists"
     exit 1
fi
if mkdir ${lock_dir}
then ${echo} "x - created lock directory ${lock_dir}."
else ${echo} "x - failed to create lock directory ${lock_dir}."
     exit 1
fi
# ============= bl_master_package_list.txt ==============
${echo} "x - extracting bl_master_package_list.txt gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh10570/gzi
M'XL(".>LMU8"`V)L7VUA<W1E<E]P86-K86=E7VQI<W0N='AT`&U8VW*L.!)\
MUZ?,!!LQ]L3LQ/Z-$(606S=+HAO\]9LE;J+/>7!3F8"H*M5-EOV:LY!**B.%
M=-$:%;P/)I.04:J)/D1/TN'7A,X:/R_=_:F&3VJ2%&*AM"XWOI`SN65R)M?;
MM<,J3TK9!-^5$&S[3"_58XXWQNBNMS*7EOL%#[$;C:7;B]8LY!I"R?AY@P6:
M6]M20S>9=F%EYUSD[9&UA(R56A<,Y(<$-MS94."3EIAO2L,7(;<*CS!*ON'!
M2V??N&_U1I1$[8>UC!]*CBUCC7.46NLG&>/Z/_/Y[S\MR4\U^,N%,K<XIL!N
MULD,#?V@-1FO&\;.:FV@DX7@I?PH(;:T:DUSE+]G4UI+G$GR#7:?:>@B@NNV
M?BC3W"KN4B_76S2X+,MH_'"SS^6HTNS5U'+SFQ/<G)6]:?4T]&JP5[W9`KE;
M_OJKO?$5;6BWW*>A;V!08?;M_6"-#C(EN?Z6E'.;8,&1EDZV#HWW8(FCE.WR
M<5JMB7?B_D(RTMWQ6]A\&S`M+E9A,QHFR>Q"NVCJ<_>+YQ,25B&+LQG-_0;)
M(=-WPV2N/#3(6VZ`?"\=&?6IY+=<X)"ZN1@IAG2]$ZE=ILC>4KD1B_$YDBJA
M5;2@C(WC[6.%RBU>RT0(ZN[Y;\M!OR[./S^WD&+V+:K*C.\9>3-QSCURZ7%S
MV*+F5MN?7(,Y4K+'M4.(B[B6"?66J2K]0J!>J5_)_%V783<BXU%&8N[F8EBK
M\"J&]DM'2]VE@_XXKLV-EQ1JZ+<BIR8.+)DMLC0)9<9C5<7F"36/(\QY`,^P
M0VT:JUW/7HN!>C21$==1SK9T7\-##'"6T1Y75=!:9#+PO0K.X552"'RT+7)2
MY>V7_'F38:=#&/@-LH)R08GW'P)[XA7>>@8[\YJ7U"&@#3H(0N(JTRQ]R8U9
M:D5XH)OH/_\46EJYK%VFA,;7<=/12@E-`]\?0T+<>*'A7:$MMUWMD=UX/-<F
M.>(%;HQ_@)]K2=%)QLFH[*0VZK'!I_D16P&?5B2V,(J&0K+[;Q?MK(T7I\H=
M:C]BG.WG*XDO:6OT?9&UZV@00E][=^)&VVU^9?%'8"O!FGX?$Y"O-DA49(ZW
MD\8>F9-"^'S)I^SXYQVC*;A0UU/_0'Y6"1N+GI\-*W>NPOG/N:HOIL=G+X@,
M0/*C#9V,D\9N9?E@<JSE92(8CQZ2B19%]K>W7PFMZ'Z[T`*?Y>=.K'X13HYC
M$35FG?P6W-`<V0$_J)+\<\6_,RH%:.F((UT<O6QK917M\Q$VL$+.QRI<2VQM
M[FAN>Z?:^Y-;D:NHJ890[YJ6U&/G]T:$:N"1*8@(SI<&):K(15,?/^0]/QCF
M/.W1*T)^&4Q.HC8;J(_@)!9R_L!OO</^J96GUA067!AF-J&"\N"K$U'+P1G_
M*?;&M+6CB"!%C]_*>PRYZ$1<AB[QL#(B:[!4(DYYC":%H/S1LX`YE+#$ZGE:
MO)<]*%WC;8<JZ+K@AE)<&_&CD=LBF97!<WN[2W*!Z@GS*ZK,=L&BZ93Y6[LX
ME>U)$U2'\%E;V8038=`N&)O>,,H!<NL@\7-\<(<*=E!"96@YM*_"NY0:TG'7
MON"6.LU;A9OPCC"Y78`&?2W$7\-`6.X,!]N="AS]TFLZOS`9VU,J3W,RR/?Y
MLM?<'^<!5A[`H>07%.D#1R4=84^&\W'$!/9?H58=F\#L]U/:^43IG"%VXF<K
M3@J8E>TD<F$XP4!_GW*D2[2H>(\#PF\AY@-QL=W6WR`?)JI;*MSV<1.-FA*V
MI%R$WNRKB%CO+18JUG48.@!=/.'KYUM:\SY\G)#1J8NN8\Z%6CVM[,GR/'_B
M4M!,3DCR,M&ZRRTVJ-&<GX<UR2QWA#"\5'"SS^@W!_18ZI!A12W/!^9J,5_V
MLR7-VM&NIU.Q\:6T,)1P@*2"#:E/]+HV(:D8+YF'C0,0#SL7RC@PT>G,I'6X
MMB_IZS5='M=3_]G#,G^>%.KJ*=>">J%O:RX;TTM>]Q"II\:83"SE!G&JL4<^
MSUC-/KQ:F>>'$Y\V;2E_KEN4;53G]"K3%9!/G#7\`5BU#/>TN$SLHX/9BN$F
M'I$V<-9OM8]%X\>PBW$8Q3'W)PZ5"9D(*1%W(!RN":;-ONY.7KT29^9FA<'9
MBTRRSB]8H.8DXG,3N>SBB%%$#F-YR40<$8BFTLR&&67'FP=:E`]^1BL-Q0PD
M<N:NCKXW8K&"',=E[O?_6T`<@H`N,B(UQ'D6P(A@/JJ1++&%N%KSI*TQ'``9
M1<OO*$P8.$'<N=8+A4]?2'+>&3RI*`7."QX?N;2X*4)&NU.\O\S3]G.<.(YS
MQB+F'D?/^3B4_R%F+MQB]J9@3.7_9'3GF0+L#[KSDRRV>;\<0\D!;4"]V&0D
MKW$&L2V>"!'\=76:%2_J;=!!O%"FQ(O_B;1\Z+"W<A;W^>(2NV6?@,7"\[M`
=5/%IC8]GR\]^8."B_9>N&\U'G_\#..AE:MD2``"W
`
end
SHAR_EOF
${echo} gunzipping file bl_master_package_list.txt &&

gzip -dc ${lock_dir}/gzi > 'bl_master_package_list.txt' && \
  chmod 0775 'bl_master_package_list.txt'
if test $? -ne 0
then ${echo} "restore of bl_master_package_list.txt failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'bl_master_package_list.txt': 'MD5 check failed'
       ) << \SHAR_EOF
5f0781f289a6caea5bc79326be079e71  bl_master_package_list.txt
SHAR_EOF

else
test `LC_ALL=C wc -c < 'bl_master_package_list.txt'` -ne 4825 && \
  ${echo} "restoration warning:  size of 'bl_master_package_list.txt' is not 4825"
  fi
# ============= bl_install_master_list.sh ==============
${echo} "x - extracting bl_install_master_list.sh gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh10570/gzi
M'XL(".>LMU8"`V)L7VEN<W1A;&Q?;6%S=&5R7VQI<W0N<V@`E57?;]LV$'Z.
M_HJS+$1I,5IQ%@1#.K<HL'5/Z\-:;`]Q9]$F;7.62$6DZAA)_O?>4;^LI-DP
M/P0(=??=Q^_N/HY'R5+I9,GM-K#2`:N"8`SOP:Y*53AP!K8R*^!@*E#:.IYE
MP&%9Z=46S!H*OMKQC;0_P&VE5KOL`':GBD+I#8*XK;$2>%9*+@YMMA23(%/6
MK54F9Y-DF2UR;ITL%PW4@CY.W)T+`K6&$=P`DQ!&;4H(7^`-(DL=`/[D:FL@
M_%U9BR5;-D#!<)3R!N2=<C`-ULJCWB#@_?2:/88P@U!4>?$$=L7=H.8#6"D@
MMLG\=93`#6/:L.8^K)0KD^=2"_LEB6M25.R\+Y8J@;*F6.O\>^S_J+0F]MQ"
M:0QV`/8*56[57IL24,%L$OH<.IZ%O'!L@]UJ@]@!PD!F5A[A?D2L\OO8_U0H
M4%$J[8#(<R0_@/<`MA(&GA0*_:W&GTSIP%0.\BISBO%RM9T$2^7LU>7LO%$X
M%<5N`XSY,CY$.;ER52E3DIWGXNIR*$<#,*V)/%?N]!0VI2R`W4)\K7[\Z2J*
M!UW"[W.?B[\1#,JCB%)M]("&Q;8V>'=`<"V7DS'\JODR(^'Z"T)NA`Q.&E@N
MQ`#,`P0GK5Q5(;BKFX&"D69K7!FGC,;_M<CK@44H>_8JN/=Q8_B+6E-W!7F`
MYCER/%HRT,;U:]0D_6+P@]LJ"\L#T"@3:TKW2X#9.VWV^FA1.[G'_O;#>%Z7
MQFFF5`]+VDY\0N'R@J)F:;YS,B_2H.]45#</.S4=-A5\(]AM)<L#L*S5//Y;
MJ1C_X?L=Q/?UI:.+\#J,+A_I?!Z<0+MTUY/7\S/Z\RJ93Q,$QZ/YF1^@^0-J
M@>=)#&]Q%EJ&]2QW^_"_./CR?>5GT-!V]3^-(HF[";O[^@'8^AE#^KC`29Q%
M[VHMRWQ0ZNWIA3\FPVIC0QBU1E)*'#T-F/Q(IOW)\;+$\MV\T"2^X%7(TP6V
M3EC0',["E*@SW;$O8OCY^')IB%.,9N1,ZSI*0_IDG%.D)4PW&+431<>%PDZ4
M#[AW8=3!A=W^173R(O,^`QX>6F?O^MTDOQA$NRB,EB389P,"G14]T6V!ZP/.
MNU\&;.H>';-;-7SOG%^^JF#.,+_:_^[LK0^@+PO4CU7%IN1H']X]/YH]9,;L
MZ'&U4L*>"G9-$TKHN-MSBG82*GQ(<2&];MZ\'5$G[R&5L2PZ$%'&2Y`O%Y4+
M2/J@UO]/6:KUH;N;_(I[4-^U?Y0G$_+V02_[:<9';\T5*8%UFYQ^NN.X>>BB
J=\_W?_P;A5B^1P%;:OT;]1[[LS%&C(Y?+VK6A9>J>4F_`6E3\5&D"```
`
end
SHAR_EOF
${echo} gunzipping file bl_install_master_list.sh &&

gzip -dc ${lock_dir}/gzi > 'bl_install_master_list.sh' && \
  chmod 0775 'bl_install_master_list.sh'
if test $? -ne 0
then ${echo} "restore of bl_install_master_list.sh failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'bl_install_master_list.sh': 'MD5 check failed'
       ) << \SHAR_EOF
2f699a25f95001a61cbffe4d02a85573  bl_install_master_list.sh
SHAR_EOF

else
test `LC_ALL=C wc -c < 'bl_install_master_list.sh'` -ne 2212 && \
  ${echo} "restoration warning:  size of 'bl_install_master_list.sh' is not 2212"
  fi
# ============= message1.txt ==============
${echo} "x - extracting message1.txt gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh10570/gzi
M'XL(".>LMU8"`VUE<W-A9V4Q+G1X=`!=55V/VS80?->OV+>VQEG7I%>@"."'
MY-*B`8K`0"]M\DA3*XDU11+\.)_^?6<IV3[G7DZ6E[,SL[/T;K>C3RYE9:UQ
M`WTP?ON7<>6%?J/=;M<T3Z-)E'0T(=/)6$MF*;ZI]"Y[FGV)-"D]&L<MT=ZR
M2DR154=YY,2-\YD3:16Y+];.=.#>1Y9S%*+7S%W;-!MZ&GGYG!+@9LKJR)3X
MF:.R-*))`OHW'*IT``H@4@?+!!(E\0V1AJ@K492!`Y4P1-6AVG6U;0*<[2I&
MCK.<#_[$D4PFW_>5S;=KV4'I(R!(U-<>G<H*7$`8,F"3LB<UXQ\E:R;2HW(:
MI$:5P4+1P0P7`M8<Y1N<J2(BNPYM7Q.GX@[>YZI+Z`J,\))ZP#FX)7PA?1T(
M/O?13S(KE?5(IJ^2(VL/ZV;Z^,]'>.]^R-2;%R!5=7^J9\#3R<?C]].7>A_I
MR]\?*&4#Y>@V"I/_2@(3![#$=Z02V%0E`*>1;:C.HGCM+$0P3NB8$GFM(?%'
ME<1S,%8'E/RTCOT:-#QUG,S@KB([G@*.N'PGO3VD1:'=I=I.>L?B(`MLSEG)
M9D+>4*TH^E-UT2\3N29!.GFXO3I;HR"#&R0YRLU0Y@;,^%-_.YT1$@[,CH**
MV2B)<PG(`W<7/M)O30ZHG5U:%:I!F:5D>2HN&UN9G:./VF5-M)^"Y>I6S8$P
M6U$ZUA;KE"[I$%J]<2:-ZS(MO/'^^750`I*L!IRKB0%7?LD<'3S;[]_7`[)X
M`^?Z78P^2D\U?[]'D+GNGU96%ROZQ:S5%GD3ZX%'XYR:O).Q'K,/@-,*NYJJ
M*3?[O`8[\H1H+(Z<V8K^4+*\G)9M5#UX5VLOI"`;%Q?]*X[(Z[/JN.!W?KG7
MWM"6]AQQ`V%E_,3`2T9#I#,9GH^LCTO#)-;5V;_?/V$8KC=#P8H9[]KF+5!^
M=ZG$9<^7NH/<>VE.&2PQQ9575?7E@$$7>O/0_OR`TVI+FPVDRJ;?R>2GD,7C
M\P8AT2+A)C.;3?,+NCZN1+C20G%BIMM[.?D^GQ`/-`@^F>RCX=0V#U?.M_57
MG^/KL(@))6RSWTJ^V^97G%]_,>CE[>!KP3JN/R+SYZ^7?8$D?C:^)%F/!*S/
M7^G1&FPQ9D:UPF$SSS.7R[LBZEI#VUJ%OS'G\.[^_F2.II6"UL?AOO/'TH8Q
4X.'DK%?=.W"*N?D?*^[9A-(&``!#
`
end
SHAR_EOF
${echo} gunzipping file message1.txt &&

gzip -dc ${lock_dir}/gzi > 'message1.txt' && \
  chmod 0664 'message1.txt'
if test $? -ne 0
then ${echo} "restore of message1.txt failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'message1.txt': 'MD5 check failed'
       ) << \SHAR_EOF
fd8dc11d1961085385dfc293681dba2a  message1.txt
SHAR_EOF

else
test `LC_ALL=C wc -c < 'message1.txt'` -ne 1746 && \
  ${echo} "restoration warning:  size of 'message1.txt' is not 1746"
  fi
# ============= sources.list.clean ==============
${echo} "x - extracting sources.list.clean gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh10570/gzi
M'XL(".>LMU8"`W-O=7)C97,N;&ES="YC;&5A;@"U5DUO&C$0O?,K1N*05@I+
M/E`/N?4CATB41`FHJJHJ\MJSK-O%7OD#NO^^,[ML(*$D!-(#$AC[S;R9-\_N
M*DQ!*F=G%S\F:30APND@.1G`<'P']V,7?:A@+')W#SWX6)2Y`#%3'P;P[NSD
M='!R?G;^_F<?0K-O)K0!ASXX+0.J3J<+=XB0AU!>]/LY%F42ZQB)M+,^?6;1
MZ%#U)^74"84C&]!#9AWD=@'!0FS6Z2LA&5R@@SDZKZWQ8#,(.8+2'"V-@1:3
M#I-91INFB7`RUW-<C]E\[4/I4&J/&QD30,\[>1A(I]N%K^(7\4CC%#+]AX@H
MP=Q*9U64J$!D@<@P@4P;4=#I`@5!-:P8X#!BO3;B6Q#<"L9YCI)/"7B;A85P
MQ(:$1`RTIVVE]3I85P']NAR-KVXOA]]A,KJ;W-Q<WXXOOT!:U15H9,=8`<4L
M(95Y>PQE4Q!#FJ!=(JQB4`XD&Q8"PK>KX1!&UV,*)Y'60)B*D1S.-2Z`6M#F
MOLRL#0<>970DOB;HZY73IK"?9-9/[]>+@^)OHKQE*Z'MY3&U0Y%J*FXCI$Q;
MD>P%89,M%%JBD9C`3=-J+X+V6065C911D8'P;`(,QDO@]#0/]5+T6(=K<]U)
M,XPSBT5X1CDORX9!#E7.*HD][>;1^3TG^;`<_H6SHX):->2":IXB&BJC#VR)
MGA'P3T#C";*HZOYS%Z4U@9R']E`;N1=+'ZJ[31HK0F[C-`<=:(,LHL(::O/"
M\'9&?2Y+4IX(]>(BUS*O<R)KGFNZ:TA;62P@0Q$B65W"2#NH*Q7R=VD=Z?,9
M83'6_[.DWBJ')T:]\LM#^_ZZ$.L46G*;Z`_@#_Q?N+0.A-H'9IO;[HNQ%Y6M
MO=L3A>4X,?P,0Q.:QX@M"KO09@IA8<F@#=9^*Y1Z,M6?A;&&IJ@XJD?MJ!0N
M&'1':Y->3\Z8IW\U)[X>?=[,X]C(_IA>28'_LEF&CI1$=\D#?'V!+%]$U,42
M)2=/0VV4=9X=0M#8N#E=)9SH<I!HAAU/+JQ5NA6W;*'7J[1\ORY9-`?7"_R:
MPP?0)J]TJL?[ZD>,0K)!6Q(7\BD+"\%=LN!S77)-M(."?61E1(\\@YS4";]=
2$O5H/%72;H?^`JT<:(`U#```
`
end
SHAR_EOF
${echo} gunzipping file sources.list.clean &&

gzip -dc ${lock_dir}/gzi > 'sources.list.clean' && \
  chmod 0664 'sources.list.clean'
if test $? -ne 0
then ${echo} "restore of sources.list.clean failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'sources.list.clean': 'MD5 check failed'
       ) << \SHAR_EOF
6ea187fb13c9c014f204ef6c411c10a9  sources.list.clean
SHAR_EOF

else
test `LC_ALL=C wc -c < 'sources.list.clean'` -ne 3125 && \
  ${echo} "restoration warning:  size of 'sources.list.clean' is not 3125"
  fi
# ============= pseudo_orphans.txt ==============
${echo} "x - extracting pseudo_orphans.txt gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh10570/gzi
M'XL(".>LMU8"`W!S975D;U]O<G!H86YS+G1X=`!54KMRW#`,[/45&%_C)*;'
MKRI-QJ6[%/D!B,))T/$5$M19_GI#4G0YSZC@+A9++*@#_!D(CM&Y>.;00T)[
MPIX*E"%6UT%+4%.?L:,.)(*HV*%0$9@H%XX!.*PL9COP1'?-`6@BI8\K_5_5
ML5T:E>4"^B%T\1Q6ZSN]QF(M]*4E5-]2UJ'44O6>2M$A:KH'>(,^RN;D6&=I
M9T@<PA(`G8-,/@KM67;#HCZWOSG\A)BYU[%_??\&*/#X\/`(&#K(=;.XP22F
M)]F3WRS)"Q&<!Y6?<;N4.O73,1'6=7C4_('NFX/2KU#8L\,,;=52S*3]CJSH
MA@!3RE'55RM6RO&VX;&6)1D54I_]-3;7UK%/Q51A5QK'+6IY(./9T\MH1IQ0
M1<IONN<OP'0T+3TV'N.(FWB%3JZ`][HFXU&&YPL[MA^<GBXP=\D(OL<0_6PD
M$UTJ)6B,>8.^>D^Y";9ETSHL\N/Z;!SU:.<EX"Q##"9A1L^GV/S#?ZWC)AN;
@,:@64]E!D>6'R!=8\\03NAV+=7)Z:CX!2VDM>]4"``!A
`
end
SHAR_EOF
${echo} gunzipping file pseudo_orphans.txt &&

gzip -dc ${lock_dir}/gzi > 'pseudo_orphans.txt' && \
  chmod 0664 'pseudo_orphans.txt'
if test $? -ne 0
then ${echo} "restore of pseudo_orphans.txt failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'pseudo_orphans.txt': 'MD5 check failed'
       ) << \SHAR_EOF
3b4e8cae84e139fc3907a4b16cf0713b  pseudo_orphans.txt
SHAR_EOF

else
test `LC_ALL=C wc -c < 'pseudo_orphans.txt'` -ne 725 && \
  ${echo} "restoration warning:  size of 'pseudo_orphans.txt' is not 725"
  fi
# ============= pick_cran_mirror.py ==============
${echo} "x - extracting pick_cran_mirror.py gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh10570/gzi
M'XL(".>LMU8"`W!I8VM?8W)A;E]M:7)R;W(N<'D`A5AM;]LX$OX<_0K605$)
MD.4XZ0)ML.FAZ76+8-NT2-,M%ME`H"7:YH46M21MQ_?K[QE2DB5?V@U:0Q*'
M,\^\#WG\;+*V9C*3U414&U;OW%)7T7$MBX>\,+S*5](8;;)ZQ\:L,(([4;+O
M^/^)[]CI*S9]?3Y]=7XZ99=?;]GIR?1E%!VS2U'PM17LADG+K&:\KKE2LEJH
M'2MX\9`R7I7LR^[#[>]$P;?"ZI5(V5(8\0+O6"(8C%`(PYSV3VRGUX:]NWE[
MS1I0).N=+@6;<0M(V+%TKK;GDTDI-D+I6IAL48%UILUBXI_&?@6_*VTGUO&9
M$A-GA-A(L<VM7-5*Y$I:9YTV`EIG2[=2F8!)/.:M=$O`5#6;&[UB;BEMRO2<
M%8!FQ3FH"`$`!$..%^YA?#9V:W"37&6P7^F6HM2%]9!$-5&PJ'63P+_'`-B*
M![T19J[T-BOT:O+W&H125W;R^O7+7\Y>3?M"EGH[=GILA1MS_"I1P%%C@Z\-
M0:MD%'GD"PDPM;82R'8,>FOCV`<'UWPH'WY"\H57"QTU+PL9>:*_U]*('%@M
MX,4CL!FE;'26G8R2J*6U.UC*&5Z(F8\`;=N5PFZBJ-!JO:HLNV!WHT_>NZ,T
M8ON_T;>;CZ-[<OB?PK*K%RL&6RB%</*!Y3W!-AQ6AD=9#;.(F=8/6=0]$FLP
MB`K%K66?=M]E5>IM#+#9V[I6LN!DW/`U.8^\\%+,69[+2KH\CV'5>4JQC-46
M%NT.6[(#.B>=$A>C+Q2X?W:!VZI&;%J1%\2RXTB[,[@QAVR^5@Y!^5\1G_YR
MDK*7)R=/T,VT*87)MQ*1%4]!$1WYM=4NK[034'MTK1V#G2A0$7U(3&X$,T)Y
M8V6,7<V9K%BIUS-'9@5B'^???F?QI4$R:)5D(_`]_DWQ!7'26\L*)7@5?M=U
M(W/.I4(B7K#?N+*B1=)H@L_C:?-):5[FG6OB#G2(7!B%8(^B3MMC`LY*[C@A
MI><5\EZQV&TU(!N$@&5S;9C@Q9(A[!%@E>B^]/B$0-O;L4MV2"1O?L3[5WJ/
MP38EWDEO-UPE4`8(P(8K).0`3D=(<B4M=2J>]X-Y+S0+#&.9]'7EK,U6JGU6
MB+WV?E?YM%2_(6AQB_U_X#7V%!>=O+XNG;F"28;@4_I:\94@4:):KX1!H8J;
M-$V&ZL"J0BD#15#`?;T.SQZC$X]N0$VT#<QW>+QIMMV"+DX.^+8,6H7GTEC7
M`&9VJ=>J9#./<:95.4=U&3"0"&QV<<%.AGA;%%EM=&VSK9"+)1)-4(C>FK7X
M9V(0^DJ8??>OV>7GC_]^`GH#%*6I:9T'--12I/,]T,<!/`OC>:7;<MW?0!^:
MB,D#Z[CO['?A4^.XU*-.O?DN9))$1QV+!<I&X\DXN9/WOHY8U.+F:RX/(Y(@
M*3Y#QFT%H]9.<8F>XQ>ZI!T6IT#?9!4]Q\D3!%XV88Q'?U6LTGMN:!Y'!W2^
MR.7%DAL;G_E2=\S(;4V%02F[I3Z@D'`6)D0EVV49%;@V5I9\`[RU=C3&^*02
M5H:$*L4CL2O7)O03*(PBQ69KQ!L*W17[SQJAYRAX]YE)4.'!?S'V=IFRG4"/
M0[JN:.K)V/D8&B`$!T7PC8_&O2](K0+#@S9QGZ[O+EL8K53N=$X>'9"EY(R<
M*[FH+BAR4ZI]S?M)=MIP\3MR79'EJH4HXWU=NNMSNV<#IV^7HD(M`D<_QS5#
M14H1*U;2T:!F(8@/*Y"/KLZ)<8+9I:KP$H\:Z:,T`-KC"8Y$R]"^"2DQ+M`<
M'\@/C=\"O]:_LMIHM4'QA5\PSE4.V4_.(_%BUH3<>UJXU(^]J//P.CCPK,-P
M5!MA[=BSZ2,C`!TR%ERPH\;)R?-+5)LN3SU?Q&I#$\1_]6^B;,:,I%M_NFD/
M5FL-Z3N?VU_\X^VN%MGU^S_>WZ3LX.O;;[>?/[V]O7H''L<M$UZ6.;7PG)#1
MD!730P*?^I'`)RV:/2:E4L[GJ+Y5@2%:N*T051BE4)F0.7M8X!AX#)&N)$RE
M*P?CY4M?"F,_I0R(EN*Q!K^8`O1@:3-8"K8.?O'YA3.&#T),_GYF6:+X[<)P
M,BP\1_JAV1:L?^E?R.KM@A?G*TD\\D&$!'@VZA/LXS3XOA<-^H'`J9F:'M0S
M_RU8@IN'=4U%[-?9F^?VU\GLS5_5B#T//"@G_$08)P>=?F&D+_K<.>K%I!:B
M`O2V(_,D0>X'//8"FE:RL#,F)"G[T1_&1_P[3=GTZ=U[I?K#8Y)VNZ<_V]VX
M-/VA[-.?[NZ*?/KT[C,O_@>[6_\]+7S:V]VW^][:K0."Y2E9AUV*(I]HDOV1
MH%=)P[#?!6)O,#IF<&)O5.7-W"@=C5*:AB/N6*UE1974/3W@=MS"()?ZW0F"
MH9/8*[>"0H,:#A&Q9Q?L&C%^_H,6X/G=$>5]3[/\_U0S_C2T5\HV2H7N3H'+
M*G1#/PV#!<TF5+=U]8^CP;#S/[>4+#'$W9W<)\D3YP%:FMYWC(QP:U.%>6W@
MF9"]#?R02VEH$U`$YHG]<^90/6DVQ'DW]`I?3O/3RV^WMY^O\R\W[[]^3?K6
M\W4@)IL.0P$?@ZP0A[2GQ@SAXJ$&27<:PIE"[^(>DX/3$)$1EV/V$0LVF!L3
M/)W?PLV';:\?8&&'P.*FQ&BL:&0)9TK?*<7^0"PML:/#,F:=_9&XT#A+L\H;
MS'/K+Y4"]=^976.#%<UR.*O[2PQA8@U7QR-_>V0QD(G)S:34Q82.N<VED<U`
M/FHG3W^L*!_3,$_T#Q6D6[Q2R=WT_)[T/MH?WYOCT5T("[_W[NR>(O:(/!D^
MDQ='_</JR'/I'+<_?T)^="0>"U&[OF>[8VLW_.^O"7IW`X=W!3^\)2#Q![3#
MZX&>[TN=<\3'A@S1[MT;'04)L+K+BK#WJ#G:H$(300.?5*8W&LLQ`?KN-%#U
MF%T+T1PQ^$9+FH9#I@KR5B#J;F@R'\,Y.,3M%+FSF7B4+IX29V5%Q_<[-Q4E
M_9A0[1&%J3&4"SB2T68;NC?F?"^4K3!\\86@`@C,6<L1_=O7QQ>@IS)YQ;8<
M8Q[%T&K'ZK6IM14VZTPQ-$,?:=_0R!7CT*0;._<O<?JN.J2,(D)_<1`,240B
@B-*MZ=X*-)E95S$)YV:Q2:(.1H\PB?X'G^7Z/W(5``"N
`
end
SHAR_EOF
${echo} gunzipping file pick_cran_mirror.py &&

gzip -dc ${lock_dir}/gzi > 'pick_cran_mirror.py' && \
  chmod 0775 'pick_cran_mirror.py'
if test $? -ne 0
then ${echo} "restore of pick_cran_mirror.py failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'pick_cran_mirror.py': 'MD5 check failed'
       ) << \SHAR_EOF
1eea77154b2c1f774fe8fdf88b5a8a87  pick_cran_mirror.py
SHAR_EOF

else
test `LC_ALL=C wc -c < 'pick_cran_mirror.py'` -ne 5490 && \
  ${echo} "restoration warning:  size of 'pick_cran_mirror.py' is not 5490"
  fi
# ============= bio-linux-keyring.deb ==============
${echo} "x - extracting bio-linux-keyring.deb gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh10570/gzi
M'XL(".>LMU8"`V)I;RUL:6YU>"UK97ER:6YG+F1E8@"-=V5,'0"S)>[N?G%W
M=W=W+5#<W=W=78H4*^[%Y0*EN$-QIT!QYR(7[OMVD_=^;#;9/3F99&9R_IV3
MS%")6GA:V8NC6-M8.EBXLEDZN%IX!E!24G+Q\O)Q\W$+"G!24OZ'E/]=N3@Y
M^7EY*2EY*?\;7U&XV3E1K-Q<O3W=G-F]+3S9[0+_WWI^?H'_T0.2D*#^%V!@
MKW)-W98Y\6*]BLT]%MBA')2^_710EI+L4]M.KH6)CL8B=#VDU]<1:2L.47R_
M(PLRK59S3D["2)^CZ6B=R],X?!1+"1J>.Z,)R'UE\02=KRD)*V=:YV.^,VT^
M])<BIL-K2-JQ+D-%Z$^)XX%$(&'*VTXYK=(D[VMS$DH(&\]@Q`I1215^1=A_
MRZ\W10-V`S'I8CHRH[\T60]$9$\7+I*??5<W[7]S[(\[M?#E45$&Q?4?Y(K`
MSJ0JA(>Z`5/9`F"5A$L&E.WBW`.0]?T,-^W4IY>J>UJJEO+%!W.F%FY`_'S+
M_7'T;-8V+?CX?-*^IXN"W.69]LGUG;TFIKF#=5L6XJ4CJ";U374A/@UD#JDW
MO2W*5FF)I,FX+U4KTQ*74FQYY5@-"9NY.\L(3LGW`V3!A25#J`:@9.)_FYE&
M9I&9Z<]9K,IO6MRAV\_"S+Q9BWKP#T,[89IUCOYH>[IQ76?4R3M$H$7*4I-N
MS9V^%&02G\0T&+:AEG#.N7D-.5R)NOHIPM?C`E8Y(BS(X">ALG%C(?D\9-'=
M_P8\WW8%GI>O*%N&2"F_06AGC%HM\4N'4OI=0K</#)I2-#UA`EX*"%<YUD;P
M#KZ@5L4,Y(<;=BF;T+L(_I%C8XWU(4EJ_8$LP4W%%MI=,D38&DLL/D2RN]+O
MH.*J?T-GCL<5F)2/[]$52$KAJ6._:.;">T.0P@C^;M]LO*W\CB8BYEOL*B8P
M0C&2P;L>B>MG:['A,+.P%H&`0F\Q//RQ-TRAE3`?38I#\,=(!)Z',4BG>H?1
M_V2UQO/"Z2`NJV(#FJQ=G<!G6EG`^7D@6+AC#_/#DZ89L4/?B2(+#P=."NO_
M9*M7*$SMH.T$%",4%(JUA;?%_YCZ_R,7@@)<@O\77_>MS5U\\:4S7@M.A-R3
M(>G-U$;T?B5@.E'=S<#+RF<ZJ9;8[JMS7MO;Z3P0[ZR/$(-6`M"B/)@XS7".
MK1R6#DF`JTF]21..),S=WC\NYH$6\9**19382(-[#$KYX%]N+X!/5.</]DGP
MEEM8?IS%ZUK3>Y<X!+CR"=>T1PQ6&($,8L2ZX[W'0,+(/_>8"[QN`3!A>#UW
M<<C9+_^9\7VJA<[YF(<.0S#`V#"Q%LGA=X"7"J)/5`A$'+P<^&)E`KJX&R]C
M/&]0WY1(M;JO]F2%_'K!)7H&_@+$WA3%6>!(:^')6!QB8L%8<-['[7TW?X%4
M;P'"B%@4VSZ_,14`"RCJI[;=.*C>4O30KY\>K(;F3]W$'B%'`K7F:F==Z)^X
MSPQ$;U>0#&],W;#120@J5#$:\O48:K,V5OY:3S.\MVD9VX-8(P%_-J%'45&`
M2#*,/G#<(4Z,Z'[3%I.1).2""MIYPF9RV7XT#\N2JJY)FL*>EMP2L.;OQ*\8
M)SM6UEUD=&MC@6;:WIJ.3B7*EM9/H8&R+\O_FR)_PC!5H3U"HR]+_Y@^NT(C
M<_9BP7)=QA26/9[#P:84+J=_]8!T'(VE!8U&*AR._(_(D,1D5J-E:H>H%.-1
MJK@--&&C/$O(9/-2S9BAOE5!9JV1"A?C;&'^^73[L0&T(/U1`?>]D+Q^]SU+
M?-4,3V[17EJ+=3ZA7;N[P%=YR7C?T2QR6&G?K2FE''>#=AUB26M&@4PVT^?F
M[#!*9>N288.)F87%(1<;Y7C=XH^MVQ6D^IH_X68].G%-]%AL:%^,!Z&**K_.
MK0"_1DD=L'SQ3]0O+\:Y;]RUC_S]`D[<1!O>CQ+!Q#W>U`!)]I8(`BLLQJ7A
M+U.'X>@-:.8QF1T]><JF3U:L63;>$5DA8+O]>><)[Z'Y;BSO3W/D0@EP&^3]
M`F*^]X:9]QFF\:&@]4_A0P$[NWM:PG<M+']4Z]'@`Q+7!!F]F0+2_6EHR><G
MW&#]-?N\$C1^8(&YDX\H8B=\4?4M`L!X$&6@[A-?W*M$Y'!`1]=0CPJO/5CZ
MDBV%,S`%9HJ6;@MCWQSI,6T9>(^9+</62@VH#82V.R\D)[8Z,&DH+4+$#,S#
M%%T7<D*!-THCLMIU-JR7>OA:/Y^-OU8$JDI.*/`F_"PS'[7QMS'L1NX3[J\H
M9@DRJ8->"&!DKW@TT9VM6G5A<FCR*41.!K-U#83(6G($]G[_]2`0W*&:T^RV
M\F<0(7)U0#Z!%HJ',3Z=E$F9K]UNWN-HNH;N[]19;)5&%KHZ>\W5<F2IJ$4P
M959K];Z7R(^EG0NY;??O%2T,CD$%T<=^./0P1CJ%ZEO7OMZRT_I>T-QM(.("
MX1`9S.Y+(5&A15G).T-!<Z%O>Y),.P/OG78XUU^8*+>=0]X_7K1M@ZL+9LT`
M7'65;U(MNRH4@-EWC_4:C9]N*2(E.D30F`[EBU-OG&WH"6*?4ATW4;WGA.6E
MW1LLI3JTE?ME/\69[]2;!CD`%1W\&HM=71;FG##W@_'.$X$<>'^+BL*+^U>7
MWRGB8<:#3;LP.QXJ(K'RDIABF?/`5"Z++L%SPD8<&*/PZ3V)*C".'E6^(7$V
MM6N7%/!O9/`W^J'G5LG[5ILV-I$O+],6-;+WP`+K/347BZ6YYHA_HVMX;&N,
M"ZM^MR$K.#1(XU<E5K(_7HG+BGXZX70)</<YD4T'DHW;0U8:(L*N5[>YQDJE
MB/3M4/=$*W@O#;6U%"G(GRFV92=A1%>K6CS_)1^@]*$%O'5(0GUB`5V`8OM0
M74^Y^E-KL,"@KOUM%V,[XH(,";<SG^+^D72U%#.;+(34`Q2^I_N>K""8`:^.
M)/`C*Y),Y4UUXTJ92A<N5=RD<LZ@D5B="E%>::42']IX<;9G66!0$<=(J>8Z
M'.?SN_:S#8;E6L$7_4O]%*'H:_QO2,"A*I'7JA5KK\QUNJ.%VSJ_!SM:)/\E
M8]T(>KAT@?6Q"\JOJ&M>A4O;-7`NOSE%=?\Q'0X$RJ%[(?OI]P6-9,X@Y:HN
ME.7\VF%E%VF'E?3L9Y-_S]^&5C.Z&-KB,"\;S2.+D\M:LA-")UITFCY7A@VZ
MY-%F5IEGJ/_!G=)R1/>UE>COV"Q!00*U*Z9G@R/$@5#98:D\J@'G0UI++-8E
M.^,5Z=0SB2`3;97(%G2-CA'XO5XO\4\*5)BDYFJ2+U63.GLHJY6$2X>"44Q#
M(69)SIX0X7S(WA:;/?ZC]^8:R=U%'T*_:[<S(162%6@L>""S\,I"SC?Q4LRM
MB0HHCDG>7CW73`0_[L,(Z&<0WS-"O^OH>D'\*C,`)L_P\L@0EGC-*7TX^<9_
M%!JUY,"K7#[,$&IO]0.$+:Y'<:R7_HJ4_U,ZRU6*19**1K9#=`9R0AZ[4-8C
MMR-WU8QWC\]6DUH6B#8O%3*6_%#[,>2'6F;8-9S]BN<=C00#7I"K8C`,SSE'
M;8?+J!)'9V&/+"B5)1\>&/.=C*0X2[92&#LEW=I7,9F2W<-=,<Z"^G=9_T0Z
M(C[>8)`L9K(CZ<O*@L-:<,":]DZ\E%QT#]$9#`8F1VJ%`[&XI6VU1=REKHGS
MC$)*3WTW2T4LM'6/Q^U&+Y;JEB>3O#%W4GP(4S\^3@KD(-2A=S,0@D\##)F-
MDS#PJ@TD3/7S4^T3D891Z?,@='`2`(,-]QP%&<8")T$^K"["7L+DH'Z)Q81B
M2>YNXL@:C#.*3J7M5M8CUPX((1WT*^_H5Y31`P##N`9*IZHSG^'("\[QX>]/
MPX6WN4;4;BQIV!1KB4MBC'B7G23S_L\=%YZ2[^3]\RV4\-MEL4J80%A,<\E6
MG_N*'SJR-25HL,O-G@P7(]7\;,.YMI!.Z;R>)[,;W:!`-FEX?'K6;*\O`M"L
MK\G0B5\*<RGXU$0M=T57O/.C8GKH.:>JBQF\.`5DF27=F9K$I?N7R]3<<(1T
M0G++"W464`QSDOU?[*C$=U7&$^W:7/D]RO:V+0;QR8K7B+V:9;!C#"8\="22
MYC0M(BJ"=;3F.740KT<PA'2N/-6&;N]J>U]V.U<$#-G`SCLP`U^E`"6_9:37
M,.!!",%DQ;?;XH]97C>S`M"9*%0(T=NUC=RCMD%E_IS+V,XD3RZ,3]K6G-GB
M(GT#B9QA/_]MB_`O(<W0FP*VF<JPAD::W%54'6YV7Y'G&F4BKW7^HB+4VQ(R
M-=\$?J?+UCZU(>\9_EKQ%,A%06*5UM-?V015<E.<Y:[FAXV`B4DQ\PJ2^8WR
M'EY2NSZQ.K32$BD?<;SB"GOT6WVS,&7!))FL<:H5)=UWDQEU//]9G#[)&9]*
M!9_&[(Q*P.]ZDT_<B`_#39WZXYB$#[S%]UF%H(+Z%_J+S;]9)-).#>Q>#3JW
M%*Q`KCAE2Z,Q6V5Y2S:Y6.-(VWPI[.3T(C(C>FYW5)-8Z$"3A^,N!W5DX<';
M&T$QEJY?<4_?^K/Z:B/XBR:0QYLL5`-3PSAQ",82O2PWS<FAPAXDUR-!R["H
M"&<'`W6VP@0F5@BS9.(B;[3?1J+C:7PV+ND/#!LCR:88>>$?Y>5421`*K36G
MFYO\F,">.X[:K4!SF,7$$PU$SY_R:U:=BA_6;J(132O?E.QL=IM-_!+:KAVX
ML&,PL[=W5;X_:8C;*V;9DC\FR*W3#?*2"CN!"/ZCCQPYI04O1_5P\D#/@=&!
M(L@SWT-KFA8_RA/S^.8D;Z]L]J.\`.\)>QC6DHEN97YH+5TZV1&1RJ?GBS+A
M8E<W6IIS50QAPMT.:+FGHKB,5HDF`BB`"R4A;CUYY4^B%)&PZD_[3J5ZK4-Z
MTO+(=O8$U9/K/Q-G&2OETM_9Z$U(/UR1UPS0(&W1)F%:9X1WMF\?(_E2KLA;
M_2.S?+7M1&5N9A8ILP?U=@X",UBW(]7M9&2->([-'DO;E\.\Y;\J/X+P\.S1
M,TLQS.*WHG52[7_#[<Z\F47>ZMTO@BFD/^!-2A@J]&`)40BW"K6^"XP"ES/J
MDE12T7/T!-P,0>.[U+,WFIKUWXD@.'6\,8^1PF[66S4;Y(J;,354$E?DH6<F
MD^9R43T<>-57`!7)<$H?X\ZPMKTB$GF=1$Q<`5H09S=00>IJ]/0S3TRY*CXU
MDPIB?P-E%2YE!5N:;OF@1(&OJO20&U9]OL,6/;+'&$RVUR;^C_<5]HK@"7OQ
M7?<G'"(+<!J^L==FSEP:/W3V@?OB:P-\\.@C(+]-EO_8[#DJUJG/^5]DZI]5
MZZQ/#%I4R>V0L[D!$IUQ[V.#3[+$%4MC%1+FXV85S="32&U\U0(NB>);ME>N
M%L3U:L8%E^,!+<=VY[^!HMU#%N7'NU3E<U%^X_`S5\?+^5]4Y6MF'G[#)%50
MBQM:AJL(9;#`OP1Q=-QKF,G>4(6M:M#?WUGHJ*:Q[CC:C/N+T?XSJFAX"%9-
M)8&.SP,DW^>DS_WV2ANB[1A]1(\.-'R.BPB2^*RN6MF7$,*>0G+/'VE](R&T
MB#AS&XOFJ1,:15?H,")V5QE10V82[5U+B<^.55:1I?$APH2<B])2$Q'?JAJJ
MM^P%.&P]E0K,9/$"'E%^Z3O;V?6*+2-,D?-=B6$T^JLL%90LF4@1M?I_*&(@
M9Y5Y%'V-05UN*U!MZ==<EXIEJ1-GK?]POW_=^@(>-P2GPD[;78M/MV&/7\*`
M6.'51T,5[R?"0'@,1C"_<E+XD,CF*]+<L"3,U2?Q;Y!#V`,KH<Z?D8[X-1*J
M4TWEZ;FG!@@[:'Y<R+]V_Q--VV[J.XW8AT-F6*OHC+XT8W]?@\H.?VOM#E.B
MQI'^@.VY/D126L&-7H517]IY9H.152%8RS.5\!'_M+81,=@"8]\'V*)22JJ:
M[?603UIYUAJ]DG\AU2\LXLRB<%RMI[8Y477^;*RS/F-B2'*U!)^MN"C!L]L(
MA">#CJWJ#@F>@2ZV>+<XFSH0PRR"XYRB9OBI4;BS1A_P9_^C9H0*ZR#>9.0,
M+$?1+#1*>4B1:6141C$R!Z[M#WI%'@3EOUAB%8PUZ[^(K!2B93=PLC?O-,><
MVGP#'V=M1=L1-4N4-<M*Z/N?V'<N6"P!JL&BZ*"!PB)J\D*.PL,':7?']7IU
MO!:#D<;/T;R)SPW:"$04+2>:?#X[=GU^QZYC$ADK;G-Q+#W%M(*590-=R31M
M!4`<_G:/Y4WD$!+9+UF!E2!HS9AGW%.O`HZC8R:<HI&#-'.=%J@^04PYW\W,
MJL4N/3#E82(*[M:XVF!O7E?[_"24KQ`8QXF&ZK+$2[@WV;$?B-<9%K+1NM#D
MG&!PZ91%YT`=8WQM"BVCR]ANOR696D"%"37IJM1709TVVU$/G`=]/(F!R/=.
MWML@PG_FAORV,@\%A-'B)7[:!S6-SBK[29?S&R`@*5,RY^XA4OF_+4V=Y)7/
M6U?S7<5O+E4ME6K1@[Z\G=`SGQ_V8:Q`BU_>A3OS=5ABV".UAV*GYF;J98AP
M>2Q$@_^*>,W%KOO3F=<!"P`^:ZIG(=H)R?JWIU'5[,R>$47M]IA8@$)8&KJJ
M4E@4VP1CYU<P<_?GB==A!F@P(8X"S$V2J?^5W*F;P<IHAFUC8^GH\J(E_)`C
M<&>Q=/FBULUH[+<(YE)@Q3.)H,$X\P:^<:!0<`6)&(J4C/BS]@F%?S'YWPMV
M3ERW+NG6O[]B/+FRJZTN!T56.?+H'VEJZQ`G4?+<]1]U\0NC)+QC`]_M?/Q-
M:U\JIZ`!5_DU?XV237Z,-=,_Q7YHCD]GOK+I;&;Z:R,J^!VGLSAZ],<$A+?(
M=.^G`3@()_58-?-GIB.EPCJ)@CO?4#V6/#&M1?:L,GWFE[(&`2]81;8O&*GU
M>A&7QO<#I=C0B'U1XE"0@J*12>;O$-UV,-'NA6\6CP%8LR&SHS`2W:&GH,,O
M@JF`M$9^-L5I$,;D7Z:!K0[<ODS)?8@P>1FE3V=/6M:QH54^P'?F#%#D5<"+
ML=!^]F1R5U2]2,:!!;\Q8'6-)'"L`76)D\KM47JJ*[L*WG'E73*,WF[6./PS
MCGPHH:W"0ZPC!6"9-!$N'TM;^*+,&C_/TT6VCWT<G"=J=S/W=*T9&,9X[_>Z
M;IT;++7KE3-R<3>#?GH=F\94+_[XA4:U5#>8F4;Q1".\$OM7V79';[;08M"L
MJ%SR#Y/8VUN$M'0ZY*G5Y1+<S3]27$)5XD(TI7TKB<$?;&4;L.(7;-`J1(U*
MFITNYRK_1O22]CEU`*^^`6AQY)UTT4!W_+3-D"F2!;>FP&-4_FR?"_3D5)ME
M^EE!9M",;%`1#Q];4$%^(4$%`@([9^0*4Q>TEX'3PZHU-V[(B,">##IFB*3&
M]T_3X#YV4L<P9#=1,3[;SE+F#=6NY"/782[]!\=N-@?$^0+#P*Q:*(-K8UH!
M^AJ2;K/>BK=?"PBMPOV!3K,:;T,@O]G6BOML>QC/;?K;GSPA>,R7T[%N``Y*
M42U;B1D_XC.[X>#F!96A>R.6T5]]4X0J+J-1)AS)*[%V>;_0-TS,R^X[%)AG
MQ_]2":?W&_RFJ?AKH5DE-6ZKW.8MG%JM9<3P0:^;[1.S"=#JF9"SP$GF1CU5
MXV\YC>0H5YJ1K.%F1.R--^.8$!4A?NWTY.,<]>`=IRM<C]MA4FH@3EMK@/<5
M,#.SYE9!4VA;2X^W@-4Y$%9`LN%Q;9FQ=%?0CQ-Q7@]`0DP5$0\F$GD/A"R@
M;1O]1@T3T#A;_!>=HN"OHB&\P(88D'M&H]01G'X7*RXWRY2[K=Y826SKP;G1
MA4/XO5A<TA[YW4VTT<1+$556+[+8'4I+GYD&9,9M><RNC$)WLK7)Z.`?'?'(
M"DMJ>VBT15@*UTZWL=+[)OF2IKECW9J2*H)C9ZRBR8@`(B;-Y5<7'@MBAJLX
MPH5;QB$U;:.^,RE=\65>[U`KE,$^L">SCCW"OX3^NH[5_]3O>S^'+*#84Y_H
MN8)FN?)T&\+B<$:\Q7K71";VH*[[4TIEL])UE:Z*Z\G%'XK!Q+5/ZG[&/Z0O
M<%)>546[4-IP4E[T-2@-<X`V/K5._BR`0?8Z)F=\WTK?X;8DAF+HWSZMF]OA
MY?5^;=4VGSPI#6EJEW-&IKU>]_O?+X6LLFEPACWRG0>;DT0WE-;Z%4U+WQAV
M?R8'+9>$JG6/1I%)]V0]8).E]/=&9S<OIJH($I_4H*-;?K_;S^GB2`9%,8?P
MGJ,H1@^6.7IOO`_&G5G1!@67")D7\2]4_!TL_8+[!X^(K4Y%A3#,CT2"/Z0N
M&\5-7LL#WI#O@<;E9(9`0[L:17^\D-F`X5SP&7=#[P?BM2/8=JX048#S3LV\
M-JL_\C9.W-+Y&3ZXIKFUJXBHY=CVH?/\UKFWGI#+$MM%P&1W'<Q2ULG']Q'8
MA%EK`&;R)@#+_1A.113>1PCQTDGQQJR49M]@PSJ'M>6(:'@ZVV!#P#N>7[$P
M`R1B2[']<"MG;)U.]A#YU:XO!;V]$A)$S%Z5'.0:4SEHCO^:;.[!1K6,$3NN
M27*$>\IOF*2.)3#1;?2[FXPF<CTC/XYDJ#+)'V4@W64R_(2\G:@V+8-^I9U*
M*8^['M6N1?@YO>RRP_+%$L%>X?LRL.0OPW</0OA@6JAEM!!:M-2T+;,&YM"P
MKLPB&-$-WJV2J6`#;1RN:=.*CU%5W_:DQ;R]L[NC]WRX[QNL>D[7259`MJC]
M8IFLZ<RM=!ZC3G83)M-Q([X']Y:42XUO?^F*Z,A0UX*%R6[N82<,P\Q&9B5P
M,@KV<'B_=NP5&8/.F@A%W1@"!A=GN5*B@OD[!.*R%X_N"R=LM3=0(,(1:ZYJ
M;O'%I*W]#U#2ID_36XN8T-J?:N%@M#,3&ONPQ3D!K3T'=P*1OO`P>[M'JUH5
M*86"[#<.L?#$-,%LV`P*ZS'&ONL!C=P:,D4WAZE)GSMJE48>S/'/`$4;1]#Y
M6AHB9/$5`AYW5G^3:#H2,;J_";L'`T84<3Y.'TH9P5:?F!_"$%":*`3"=4WH
MK2]X1O=@F'KP-L3\`U1D^M>R]NOL,31`**,GKJ(VH)`Y'0G,.LKP^B,ZX&HV
M#WGB'<Z-2."B^'DRLQ>0Z`V_89D"/QXPC#\]D;08WGW#3UC]TX!'@J9WM$MA
MO:UPTH1,LIF()GRGIX(F5912#/Q\^:2H":8?X6@,62`-8=LJY(E>J.7QW&9&
MOL1DW9;1\'(TA)>O^S&2P<7.R7IP&`2I]NVX3\:[&]"RN,#]Y.SG5=6R=)Q&
M+AY<,$5,4-LRX>\L!P]!#8?_)(E!EV)W@]%E_8+?TXT+=-#FVJO]<6'&L=%]
MD;0P)-S0V!2\)(&B0R_"9#;!!VW6E2*=`S3[8M*;2P#7J[J%V*!]7V]0^/0G
M;>W!K1K7!HF"IK+N\"O'P&[<;F88#'<8JU;-T,VI^?A.A.`/LD\E['_CX*.[
MM:S$7VG0V[FQAZ8N$@U_&#V8N""[N$F^!+)<]'V3YR6\J)9Z=L:TIZHBKH*"
M+9H4H>5X6^KSY<6N<[&=+HJ:YJ$]Y8<M^M-^"X><ZU+GLJBZQ=0___/3(?&K
MMY28!U`23&5'=ES!WJ'L6;KX.;KYIG>U;.Y&3@*'`_@K$?LI,1%E_H6OVM"$
MT'&!JK*\91(ITNL#A`KV)X:,N^Z,SA[=N_E_YUW'G`;^%GX@T+"T9*:<X'>I
MTXTQ/W^/5#JF[KS-A:*H=4S@)X66D9@7>,(@<LBIYT5!EP$/2:&1Y*S)"]CD
M>#'WX\"+(S\]DJHWXAR7O:)27KD*)I69MM;]T?\R2H`0N?:=*2"B?2-']6F?
M#85OQU#C92/1(71]L3^_K.Q'AQ07&V73O4!ET+NY]#-N'1!C_A.$%%!D_@WZ
MME54[N6ZXREH`B7?1HI$E2"5ROE(3'6@MSP.8EKY\U`&B0V_-5R2(!RMO0A_
M=+B\C%/E\JOO/3'[L9'\OA6JU.Z=]^('%4SIPG?+AG:1/9<LPCS&7+B1*3PL
MXRQ]7@\1>1>GB[;`E..$>UZ:$.O@9J9EY)R2V+T]*`R1"QD2&3DB\@/CLV\8
M%,-9B#-VJV=_O):G?(_Y,5)--:5<&'PV#=6?5M]*T-P6KG6*2#^L,UCG:NTD
M:2=\"VF]''$6?"WN`B4"IG/VK0^:!9!\DB_[IY".^I=BQ)2,,)'EO&D%0*RP
MTU];2G.CG<!'_^*I$-_JF%.Z0(R4`M_^,.S@:B2S$<]X6WV#R?J;E;72IT_&
MT8-"W8Z+//7Z9)X]+%+PPGBDG'0D*WA;5#(C*;'2U8;:?#6'*E$9-3;>`,IG
MLAB(MB$=W/$'83K(%$29XTKB/]-0GGH';IS@_RO%].V>MY(J__V.E*;^=/>M
MG3[WN$SI/956F<N.%L"LEE:-;4$'1[2[T7$48+G/QMX-P+@NW8T#"3M^E#>E
M<9=E!+LV`I6W&,O`]1)#;29[[6-O&#1(<`B\`1YMQ5:X>(%\%AT2C]P^-B48
ML.ON]`?Z`_K0O_/HT`!7IK*>USH$H3S=<S+XA0%=0_[W7D6RO@9I>CTZMI>.
M2GJF^Y(MA$(XGZ-?`U=GD2)!']1A$B5^4D])[L`$K>5F(SBLE5T`]PU3P$K_
MAW?>#VL6?.1/)W)=HG'<RE)8N7/;5PF_DJQGT[\-G5;4L="A:(0#FI>51;CI
M/38.]?[;Z,-]O/^.@:9<1-R3P<Z@5>:]SZ>$Q+17+A(NRUV%)P='XOR)Q&W@
M`NA@X,>U)ZTSJL?%"!+3G.%].'/8:IGG89MED0$/OWC9[OK[/;I.1\U:0"IT
MDK_(B4$>O/'OEY>K;IL>+WNU4,?!@;S>">.)HVZ)EV_SSCL=6%^E2M8?G]*8
M$7P>8>V7=TCU--Q]F4$,UN)66Q7_N<R2\`S$,YN&[N!_T^B]?G>N\VN-1@^8
MB+20F5"<M87!>G/?&9F%Y:NNF*QAW\6YDBN27/Y8;D14B&+E91G')QQ;7#M%
MD\JXSTYO##'[`^K[!Q6T[W_BHQJ/-^+3X"M6AZ&KD8]B6O+(OE=*<8&8`*3M
ML<"?3@Q%,W_Y&!?Z7HK/!/<"U*\,@9C*>>[?NU*W5'&<Q.E=)!6-F850^`MZ
M>"@S:F%I^K@;2MXNE;HX9Q_D<0,>:5@-P\BH1J=D=\\^!HJ(K[SSP]_H@\J,
M;$BYJB8`<G*!4AW"9BCQD1YSG_=7Z<M5=#2NA8-S!]<>L0:7[5/?-%\5>+J$
MHO`=_=$7,5I-?Z9@I@2I[LVFAH]J)7T1(9NP9\-7]L8X3.T-7+W]^G-M3/6C
M^@_!1</(("XSBU<SR/DYL_B5Q,R@+A-*]63R$8<:MK0S\&<[`;]]-\W1A%\!
MSPJ9U*["15?7HCG7"LI1TO@K!?6231.!3UT&JJ+*IW(.SM0&DK5?V>GYE."B
MRV-9^:"ZNJ&G/?;>P8[RN*G=%G'F%MH+C['D.-#D'4QZ"JR%2&!`?Y""`538
M_TKG(/N<CU$07,'/)`C$JA0B%1KVJ6!BM+B`H-3B)@45@FS\+@\-GS!R0:-Q
M/'7B+:B^H,9UC\@#$,A;WFU6E-CIJXI/(^"LTW[--<;5/L]CPI_UE0OF%1!E
M[_VF6?;P]36[GN@7"T>/#ZP#+`K&U=U3CFL^CUM=!`Q?>=I8U5WU)/QXCD5$
M5'17N<XBE<D^V$)W"C2DN?4;A=2\/OYDWF?3)_%8PCS]61RJ$&,OL"U6,=4X
M0"</+5;VRTFOBCC2;^,,3`[R#*8N\T!B7*?\/WG?<'1M@]_0*^#-8?\VK]<0
MUW8]/Z4.U)FM22/M&FBAX@"1S.*J:;*NIZ#L2B;;\;HT$`BK%OQTBQC@]8D7
M`OQ_V>&!:0%IZZX`MHH551!C7D<-VO50SH@<<5+[T]):=+L'@4IYST<]88(2
ML)\%2G,I$@V)8^FDQUDYG"\(>M"B,4Q4J?BZ),F.MRK+K?<+N5?K"C*?$P?.
M-//<A4GDA"FET(:=G("@%DO4<V;P.<^6D=M@8\QC;N"B!4/CD4\D';"S'-9$
ML00'SGG`5X]MC]T#VAR;;/3G3^J@@UH^WNZWU[;F)C+%^4ZY;(.$+F!/R0L?
M@8-T9T3YNT/,TQ\WF[F_-O"&HE.M8WZHTQ>]F!<P<;W#+E'7ST*>`EX++`B7
M6G]<]M46404&(VI21AM.QI3)X>/5PP6+5>\/:E)7A?W;[O3+>LI:-6H7LPZK
MJFM[XA]C:TX3"9<:?AN;D0>PBYB=>?'Q]X<CEW=;S[^K88B;J*ODJFH&'F3]
MJI?^S\ZO"J%#BERE,<C+7`UFS>L2'\_MZ'2F%!$.*R@W-D*TBFL<WVI<D+)X
M:8]CU;W\ACKYW9-&.IY/[2#GE!9)U5`<*,=E@\.Z<V;U`A5]^CNB'N`:E"*T
M&VV&F(K]R;7&RJ=(H_`[H/_]>^JZ'PM>8\5EP\/%9<F2\Q>@*@ER?+*Y,=X_
MRNJ_+#02K_%[)?T-.[.J?3**\?%'Z=ZG[[L>9\%>UR^K,;4@9+?I?BQ$":C)
MX,:^4FS6#8DLJE;EI_8PAS!"3F\WI_,_FU+V.^\N;:Q2!P0CV]@!BIL_ZMVS
MJ]>@;K%&F)]FBFV]NUX+:0=+RP-=DH''\*(I`ACWAH==_"<NQ+I!B6$FW;QJ
M>V?'U%/4=^'\6TO`?IY]D``"T38PU`KJ]ET$-G2;""MN2N%J-&WSO3W`*1V@
M@._*_'JD+PYZL*S?(S=Z,8CQV-MX]6F?.!IK`[9KC][IQU/6&D@,WBN><&!]
MFQ-YK*0.W?[F\.VZOE+S6FT\X_?R8<)=6KL^/BGZWE>2AOF4T0/8$%M,5!3'
MR,-;U(5QY-#+A=((B2`-$PC?`M@&>)GWT6;^/!VZP?'^OYO2=0BBM(S-#RA-
,**C_`MC.ZC-J)0``
`
end
SHAR_EOF
${echo} gunzipping file bio-linux-keyring.deb &&

gzip -dc ${lock_dir}/gzi > 'bio-linux-keyring.deb' && \
  chmod 0664 'bio-linux-keyring.deb'
if test $? -ne 0
then ${echo} "restore of bio-linux-keyring.deb failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'bio-linux-keyring.deb': 'MD5 check failed'
       ) << \SHAR_EOF
4506945fe703a3e521fb55b146cffea7  bio-linux-keyring.deb
SHAR_EOF

else
test `LC_ALL=C wc -c < 'bio-linux-keyring.deb'` -ne 9578 && \
  ${echo} "restoration warning:  size of 'bio-linux-keyring.deb' is not 9578"
  fi
# ============= upgrade_to_8.sh ==============
${echo} "x - extracting upgrade_to_8.sh gzipped"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 _sh10570/gzi
M'XL("-*MMU8"`W5P9W)A9&5?=&]?."YS:`#56VM[V[:2_ES]"D1V(ML5J3A-
MFZQ;)\>.G<2[KNW'E_;DB5,;(B$)%44R`&E93;*_?=\9@"+E2YIS=K^LG[:2
M2&`PF.L[`W3I0:^OTUY?VE%K29R.M!7XIQ@IL:VS8%^GY;5X+LH\EH42-C(Z
M+T(A]@H1JUREL159*J08J*D8Z$19,1WI:"0BF8):7PF=1DD9JUCT9R*7T5@7
M8:Y,TO7C9&(SH5);&N46=2L(4Z962"M,EA6@(22H%6J29T::F8BU45&1F5G8
M(IXS,9%C!2ZL2@9!E*6%U"F6O%+&:K`WU<7(LZO22"N[@5G+37:POZ&1L;HH
MLHOGH1V)%]43^H5%-C?WF!=:[U=EK1PJ462BM%@"6U$I,3\CMAN[",.09KX6
M$S=C/2RNF<*.ZK.T'&=C-3,Z'4+NZ7Q&'[)/2/:!?QO&JD]3#R!HFY4F4C9,
MM"W<\.:3,$H4I(^QKXZW#L1$&Y,9D>MHK(PR;CS]NHB,3"_<ZS"?\<ZD+91A
MP=`&:_K]Y&+"[R[\NPM>B;93O=>I+60R'\?O673BR*HRSH+,Y",)K=(;,6"6
MTA0[\QSQH`L_R`E*IC/L?F55?&H)_!DE8Q'DHGT$8X%UI#,2':F!5`YA*8BO
M+8)TG8>K:)2)G_FC]:75XI^7,YC9IO@L1DPK$L\?7XKESGG::46R6-33O1,\
M7[2U-R5Q,L5`,)<D,`#9-``1B!3V*\MBE!E=R$)?*=$O"\A@K&BT'HZ*L'6\
MN[5_=K)[O+F\`AEB5O3P3%P6Q4P\>=&+U54O+9/DLOECE>6*+]#\1(G<9)&*
MV8>RDOP%,AF4:53`^BW+FF0G^SK1Q:R%8:JX\";#BIJ+N#](Y41MMA?LZ9)=
M__N'[QY.'L:782%-./RKW>()>B`>B/<B4*+=4T74DWG16W94VN(#Q`]AI#QR
M142QJ,;@Q3D_%0+DL.$K.1#M^<3F\HNV'8M5/X_5TSY,8M+^0`]+(VF[PLHK
MN#Y"QRU^>.)`.\;-1`2#>LSB(KTUYUL\<FDO'<`IIB,R$.=,!45)\GW!G^2>
M?JS8`SME0@R,V1!X%-1!'B<&)IN(7FE-SXZD43T758.)3&%UIN>HVS`:#-E*
M>!F609)E8]B9T@:4T]BO%6?*IATRVY2W/NR'TD0C&%E8]LNT*,,(ZV&+H<B3
MTF(\.$68+(Q2/B#0!J0XVCO=\CL@'LQF^Q)""2(980=YENAHAFT9518ZL7"&
MH5&Y"#+1^4.<?WI^_N7]X^`_/IQ_+][+X"]\;O1Z[_]XOV$1*]3&!SSH8(Z<
MCD7G4XY85HCE@]=?Z%F9ZH^7[<J08$9_P0B8`S*>SY_QZ-+IN7KZ64PC$<`9
M'FR*]=K`OG.C7LDTY7Q!"HO50)9)I3/DK-\U_&6LP'KU*AN(45'DX/=.T87M
MBO"[K*24)B($)XK\K']D$R/.VSO9-$TR1`?2+B+0>9L2%@>!;%!,H>?*A.&G
M"IPA!^%[7\$OU7P%9`X*ALYF7.JAY6%0+J[R"[9.(?85;%SH@NR*'I\QQ\)'
M8&=O/F'3:Z.0$*P2Y`1AZSL*=+?S!3+>G<[@0FEBE7<["^=JV^[7Q-9S7WO=
M6[JCR1W;>]\][SWZT#O'WZ/>L'/9;2,:?"?^5:[@RE\H#N[!H#4H8]=#58CC
MN;O)9@;LLDM!:-`!G-+2J)CD)SE@*B,C"L_)#`+>9N=#4M\#>8KLFCBO7)O!
MQF0FH'>*LMZ3*'6SX37SZCRP1I5?Y3/D@O2N!'Q9AU3O"=&B*]0/8/SMY4_N
MU\.'8NU+^Y8K>`5-I].0<HH-^T;;4$9A.>X=]]JU6OWXBO:"9+<@T%09'='.
MTR+V.^:\TIH_6EEMN4V2`R"'K8#:>EM\+QZ+51>M*0,1O!&75GT4RQP&@W6Q
M?@FFX\RS$*289T4;SVQ"7NK2>)RERJ=Q\9C9PI_8BHI2)G-8BB126.1H0Q"`
M;<(Z)YT@A`$+^H%L(^M/P\=/7]+N*B?L4I061TXS%6C$2!='ZC6*TH9L;W;$
MAH"TVY=]Y'&:GMA^4'D:6=I>9\+)GZ"M4->P+@QDI`@;A)U:>`-R_]&[WW:/
M3S8OXWP\%`%"A./"^0I$`G?YXS?'TH8X7PG7SE=[Y^N]O'/9XMSKY@'T3G)$
MFL!S;\63\%GX8_!8`&0NNS6:R7@>U4RU[0KS5=N'[*IY*UJ%H&-)I'!)IKSJ
M\;M.8XV`HFR[09=]:D;$B:V2(.4("9FD,8.#]A6$T%"(#U^L%[%R:DI;S%;#
MFF"#\BG"V4`;9$3LEN.WBY>L(49!EA.S;<9%!-,<S-;FXO,MUFYR[:,NSZ1D
M1]1Y$W8&1#M!6#B=KP4X0,D$]4TBX0\C;(1L',.QRVG8)/LZ2Y)L*BB$4X`V
MI4-E71=@Y("(&=5';4'AWQ40E%V:!9>00U0T-T52P5`&`[M<0[EPUI!)M550
M''+VI]@(]\L=!/=[AED[1'$`%:6*I$AE%@QLCSD">O>F'512<B58,GL`AZBC
MED=4-W#-C;FV#E:8Z^./6!.\!9<#L8GY8$J@*H6?0<@((=^TP)IH,^T5#U6N
M1/N/)4NV-VN45DC'5X!.U;3SSW^\/\H_L'0VV]^VT,^\3*7K(S<W*:Q;?K7*
M7W]#)DS5M+7$4R97WRI%FO1-`VLI[QP>['I]53AXZ2PEUT>NG.A43V320Z!+
M8VEBSGFWH4"EK5>4GTE;92ZVCDYOH'!2@*O9;M8:;E6"EY2L@YFWU)HX,[FX
MUK&:9%>T%E<[A<E*6(.K?%S8LO,%&X0-S5(^H@8.E""9<(/`9$F0RU0ECAUN
M>_PI)[;A.UWA8I8WNRMI>DDV[$$N<XOI3<@M\?2^I3-;P`#M1RR64)\A>!X^
MO?'4<8?GK08K572!\28`T=P],0$L-PH^7LD$E:X06]0Z\0L-92*O9P%J#<3O
M`+'&T:(\-`4;#OCT2<\)12_G[BYUH/H*$`HB1=/N(=3861#DI1FJ:F$3$(CQ
M3/W-V$(/33!,]&2BC-MLYW9@Z5"%#P_8@9C/W*/?M)J^*<8_5"763D90C,*"
M[%.Y&YFR5A'8L:.70KQ5V$V:L9P2VCT52Q0&X2/SPJQ;9T1J+SF4/7&M',#]
M#H'%/#,NHBHN_5S`AF#">1EI!HVE>VM-VUU;6VO?2%_S-),M--ATG1\I:28*
MP3M`V<9XPN4'GS+F*>*>W'!KU3W:A9+4CKJ/&5`[.#P5[W9/Q:O#7X_V=T]W
MZ]6/=[</#T_]ZL=G!^+T[=Z).'EUO`>WWWJSM7=PS^K7$/MZBR+-DCC\KRZ\
ME[*CR].N1I]2(G&Y<WO_&2DKCEG8D*?.4+*2_+E=]P3\U/(Z.MK"LQ_P+'H2
M/RWQ_<>%]_](53\2*Z0OF'Y?]Q.=O7Q9E>^,930U$Q'J"N9IJAP&/-KJ4H$-
M`YO2*Z[B"#X_6,4:ZUB#*XI_B&V@:;%",R<4+:D7R4-^PI`W638$['HU,A2A
MB-JI3,;B*"F'L-(5WI+(TF1&$YYBPO63849+BQ6(),OQV@&CUZC3#_Y);VCD
M,XPDG?VZ!>7L*#LNLKPK1EF.>H9:3U+$)LL#+.&C!K4%6+1O4F*$OO%*W+1D
ME.Q!`S8_HHI2<GT\L]##:^K/J2RG'B64"B61-S#.=DW+[7WG)@D%%1*3[U-V
M019Z_A,@CD13<E?,5Z;DAHS16R[T[+[1(NS=V^H\S=(9@B459S'WM<!G2H9#
MUM]JQ)F*?%5O([%#*J;0RA(PGJ!88:SL6\YQ'-!DUH,FS8FZL78;)+_B.-"P
MV3OFTR*D9^_$\DKJA`#+'7X`A-5`:=O[\/P)X>Y1LV-UHQO53YZ'57$?A]3@
M<D(&65^)]`D6IQQ4;H8';L_3.OWL&DIGG/:`&G;?OMIB(V\R!O:C*'T/@=;2
M"_QQB";):6JZ.[W'661;WH^L3B.NHF5!??W"U@67!^"$+RN/G6(V=M;O:SOJ
MNN)>^PYM^]3,/+"EK==@_[B:C%'P*.H`[0V<:`:2^EA3U8'"JUZ0[Z608Q=9
M`K%1_V5>MM^J[%&M4R/EQ7U2Y+1(R19HP;A&YB^_H'K<YT?BF//F'+ZT8/+"
ME^!\',,.X1LI`#Q4$O5H4&!-]/<#V;F?<.CY@?_[U,L*X95D1;&F8;X5ZS<%
MI,F%9_,:#W8T!9MPA>O9#;BGK2U)7M0'()@=9)0NR?!;#A&0TS16A-/FN=R@
M*%W[_U>'3J0I82G(LASPOS:4@ARA6#B@:V/\^'55U0$H44,9S2IMM4-"\752
M<6]KR+DRCV_]4B<N/1OE@H#PNJ+`[;M)[A64+A/L(W6'`=Y$9[Z_B-!,'0:R
M!M_`(;AILM#GL#`SPYK?7L5*3Y2IVW!=W;0:1$C.*!=,Y!M`-86[)K+U4"(C
MEU*:6F.$ABE79\ZC7;B-.,%UJU@_YI;D//:%7Q?ZD)-DX&@L2'QIR0&,UWO[
MNP*?6V>GA\AY>Z^V]O??`9X<O-Y[<W:\NR,P$HQ2:Y:LE&(P!9JL:ISCAYFY
MKA\=%66D`C')8CT@:^8F"<VC&AZ`/&S**TY"QQ^W,YVD'*=(%/V>\"(C]-_Z
MMGU"8..<`<#_A[W6W-ZU7\(BK:6O[GI"]6CL,,JB.RTY_,+'#D`DXZJ'XS`*
MIM`,/E]&G+G2W``0MM2.`Y5>:9.E%;)A>BG*)QE%*",,=Y1\!K``+1(X:&;Y
MM(VASPW?HM`1+K!*[N4;VKWU\/EB7'7[7ZI<^W])A7@Y/=PY))Q=J9$/[F[A
MH2KB`+^+W>M(Y0X[L!QI<3Z$2JT>IBI^T%J:,BKZ2(0]AR[(K-]F$CO1,G7:
M\@S/0=@P']*I#:(L';(BTHH`FO\%?Q[)["!%=AD\^UX3)9JJH%AAV'$E4Q2R
MTG?0W!ZG'$/B3$S*:$3A\62ACF>`!_!F2UFU83U-8%TZ.>&]^Z-CL6*5XAJ=
MN\L9G:FO;K3X<S/LW7&FG-_]"O1:?"3-3>JZ9R36EMIBF>GY7G75SJ9NGF@?
M.;8WQ'+>%ITCG6Z(S&B"^2_7.OP@.$(A8W0QVQ#KCQ^OXV&'"7ETN9RT^6>J
M6MSH?@%*M!KWL'TRGM(]"$`;%NEO7J0+35-`.U>=G:6:&KBJ]RL@C?M:97<0
MY*X"`53$`7?:04U-7_:ZDTI746N$"`!%)X>/4SJG<[3$W:!//'KDSG/G,R;U
M^G?/:`!*^(5JS8^8YD7DFOA=&M+R1GNQ9TW2X\ZZ(IO*7.W"_=Z*3;+$A@2H
MH(9PT\)6C<2%@I6:GI3/ZDP_/[ACB57YCNH>%W&558NE='T%H<NJZMQ5B@R+
M<8?OLJ0N/D\!K+)IEVZM$-3MXVF3J`N,M0)IJZPU?ZXW<95JE!`:[FSE>3+K
M^`,-A(6@/E#4"\UY?S6E^6BK!B0`,Q46L:B0\5/%R.IWZY#WP@,R$]ZJ=6ZW
M^-QJ9_2C$=8(=U:)C=P9*-/IW1LC'3'Y;FO@PR0A+#.1"19=:#>Y/A9=V0``
M;>]HL[&Q6T0;&T?UN>NF\Z]V%57^?0+-1B"YZ['K<J%@=]TS;.LM@B.)<L\U
ME^!2D`['>?(V.H,Z]"<)F$6]:$1'I$378VJ<!+N+`^M/^."**[@V'Q@%'TM%
MN'<@.LN?3OB`ZLMYVA'![YBA5'J]<(&D+39%NS+F;#P_+XX7;FJX1CZ=Q1W\
M\V3WY&3O\&!OY\9=CMH5*Q^D7J4W..R796`I?OO#U+E0%@XB^E5K,&Y:(QEU
ML^_)B=N9"/?\XBOM^R,1P`P+W$T);I2^"T0+7U:F-@..0`"_TA)SAF4BC3@Y
M>>NN$?G&6]T$OOL8ZLPE/-9<Y?A$3)K8]992\0P;QJO8^UY]?OJL537?;_>+
MJX:I5Y[["$R<5U^]$*M?DW[U]2J-YC=J%O_PTO5`\`W>EM+EH_XU;55=%S_0
M#XRX!AKP:?TD5Y%&^8R\&">D*,IV-2:)3#D`)-!\SR!P""8:*5>0W]&3N6?F
MY\]5J&@M;7ESA^*XV]/U=08T.D7F5(N'$"SY%_]"JX1.>F$?J3^$<RV]<C!P
M71BJ6ZS8WH>%-5LSVKJ&,<,1/FDH?=@BW$:M]ZYWT^JPP`F!A!7+=,B2L[,)
M/L=L#WSK)\DBF5#UI=-!*QH!H(OOKZD%=N_UN:^]8T]=?DFW`1[?Y9]57IMC
MJ[E@A,M*B.X!JX&V=2M^.R(G$;==L)O_1&GW4P.HN:XI)]]GU!?SC90Z)%=&
M71\$8-'TSW@<_!3\:=2G+@RCWPWH9AUYS9?;2[[=VB?*+FAF?7)=CS,+H*PA
MW;TLAY2C^-[4UU8>R:0B/S],`JHI9L&36,3E9%+7]>'7Z%1SP+SSJJX[1NH&
M=H00CX^<KMIQVT&RE4Q5=3?06?7M#N;M5?RAT!T@PMW[,T.'```JKI[Y5@R+
M!<B(&@PE$C(3]8W6HX8;UO/@@PR]&E[;F$GEIN)C:FWK'2C;"/F``%,YJQMW
M0*?:T+V,;>!1E&J^4B-#36P>:4HKU>6QCZ+S_+%2&WVE!IV_S2UPH`;IP-T8
M)AW&AC$>9X8ZG[5NGD15T>C*$0%>#H8EM>8^Q>.)[;H@TN7K;=WK]?4O#0=X
MH]E87%,_J)KZY$%QEY(EP:61OX_5X(`"P3#B<L+I(!&=A9Y'L-:IA/&'UHL7
MY):??.DTZ@U.]495+3<EEH<1EPN-'OY?=L0]9&[,N#Q&Y5.6N^J?+J@A(-YL
M_V(6_6LB?WWKKC!R3#4Y"_O.*8O'KI6@`_`[_TY0"EO8V#ATW&QL;%90B_8T
MT=:V:0-5L]XE(A=DR?RZ9`7NDCB+FU`B7VRCZ[."CL8HXR,/TN6?6\)JG/<G
MLPD0Y<CY`*\!AHHR9ARB)GVR)(?&W14-CC2,P7WI-'7&>"43';<`DZY=7*=&
MK*Q(?:!JZ/9CNGC(!ZIT,3M10!WUH6%U1=>2JH::@""P+YSPSN-%E\\&.F6?
MI'8K"8-N`]`)+QT"$6P"E]F8M#8D45#QN%S=,^9[_LH?/-0G"$2IY+E$[W;$
M>%Z%R.KROFZF%-@>W<D!;=_1F=R^3!ZV?M_:WS_:.MH]WN0]V3S+DM[V_@4%
MGHMH%E'>O*!M#`T04QS^F0];2\X.=W:WS][`]^<D^([2_%=75-OCY]4/ZCDY
M2*L`:>>CVR*0#N7.!R[<2J&;CB6B:5`N#!E"1@7?U2=A`32%0^I;A553I>:<
M#BD*F%^`."7:5#%L]'K-]5\\FB-S+`B3KRZU)3,"0!1.R"K(@?C`[@%K74:,
M)/D5:?QCJ8T#&#O;9R=BY9V2HVY=)4$%,SC%*H<C.:+015B$OO36Z@`C:87-
MR_KR>7N9![<O&S<2[Y!?/!_8"QG;-*XA.O&])?DQ>11,_=(&[K[4#4'R[4_Q
M?R?/.Q:'DP61Z(3B<@7)2/QW+^3;S;TRYT/-'C/GBY9FU21^=KS=_P=J04$$
MB43/DPCH^]I-0OAK7%ZO7ZW._P>#=/V2PH>ZYFL'I-,+7X1=T/>MG9UC_"2!
M?8=AG?:_:9"=6P+L-`]!G[QXM#Z_">H2#5=`\_]0SR!Q5S.#YB4Y,;^Y%M^X
0X/"@_7/K?P!'ME=O:S0``+QX
`
end
SHAR_EOF
${echo} gunzipping file upgrade_to_8.sh &&

gzip -dc ${lock_dir}/gzi > 'upgrade_to_8.sh' && \
  chmod 0775 'upgrade_to_8.sh'
if test $? -ne 0
then ${echo} "restore of upgrade_to_8.sh failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'upgrade_to_8.sh': 'MD5 check failed'
       ) << \SHAR_EOF
9c9532c33d1e4c7f700f4976c4338e9c  upgrade_to_8.sh
SHAR_EOF

else
test `LC_ALL=C wc -c < 'upgrade_to_8.sh'` -ne 13419 && \
  ${echo} "restoration warning:  size of 'upgrade_to_8.sh' is not 13419"
  fi
if rm -fr ${lock_dir}
then ${echo} "x - removed lock directory ${lock_dir}."
else ${echo} "x - failed to remove lock directory ${lock_dir}."
     exit 1
fi
exit 0
