#!/bin/sh
set -u
set -e

echo
echo "Ensuring that /etc/casper.conf is customised"

if [ -z "${ROOT:-}" ] ; then
    echo "! \$ROOT is not set.  Can't continue"
    exit 1
fi

cf="$ROOT"/root/etc/casper.conf
fix=0

if ! grep -q '^export USERNAME="live"' "$cf" ; then
    echo "~ Fixing USERNAME"
    sudo sed -i 's/^\(export USERNAME="\)[^"]*"/\1live"/' "$cf"
    fix=1
fi

if ! grep -q '^export HOST="biolinux"' "$cf" ; then
    echo "~ Fixing HOST"
    sudo sed -i 's/^\(export HOST="\)[^"]*"/\1biolinux"/' "$cf"
    fix=1
fi

if ! grep -q '^export FLAVOUR="Bio-Linux"' "$cf" ; then
    echo "~ Fixing FLAVOUR"
    sudo sed -i 's/^[ #]*\(export FLAVOUR="\)[^"]*"/\1Bio-Linux"/' "$cf"
    fix=1
fi

if [ "$fix" = 1 ] ; then
    if [ -e "`echo "$ROOT"/root/boot/initrd.img-*`" ] ; then
	echo '!'" New initrd unpack will clobber casper.conf"
	echo '!'" You need to re-make the initrd in the chroot now,"
	echo '!'" or else interrupt recon after it unpacks the chroot"
	echo '!'" and run this fix script again."
	false
    fi
fi

echo "~ Copying $cf to initrd"
sudo cp "$cf" "$ROOT"/initrd/etc/casper.conf

