#!/bin/sh
# Check that 
set -u

echo
echo "Checking all packages reported by dpkg -l are status ii"

if [ ! -x ~/bin/openchroot ] ; then
    echo '!'" No executable ~/bin/openchroot.  Can't continue"
    exit 1
fi

#A tasty one-liner
echo "dpkg -l | sed '/^+++/,"'$!D;'" /^+++/D' | grep -qv ^ii && echo SUSPECT_PACKAGES " \
    | ~/bin/openchroot 2>&1 | grep -x SUSPECT_PACKAGES

#Return the opposite of what grep says
[ $? != 0 ]
