#!/bin/sh
set -e
set -u

if [ -z "${ROOT:-}" ] ; then
    echo '!'" \$ROOT is not set.  Can't continue"
    exit 1
fi

if [ ! -x ~/bin/openchroot ] ; then
    echo '!'" No executable ~/bin/openchroot.  Can't continue"
    exit 1
fi

# Note, exim4 is not installed by upgrade8.sh as I don't think it's my business
# to add it to existing systems, but we do want an MTA on the release version.
echo
echo "Checking exim4 is present"

[ -e "$ROOT"/root/usr/sbin/exim4 ]

echo
echo "Checking that mailname is not set"

if [ ! -e "$ROOT"/root/etc/mailname ] ; then
    exit 0
fi

echo ". File is there - trying to fix."

~/bin/openchroot <<'CMDS'
rm /etc/mailname
sed -i '/^dc_other_hostnames=/d' /etc/exim4/update-exim4.conf.conf
echo "RESET exim4/dc_other_hostnames" | debconf-communicate
echo "RESET exim4/mailname" | debconf-communicate
CMDS
