#!/bin/sh
set -u
set -e

echo
echo "Verifying that Firefox customisation seemed to stick"

if [ ! -x ~/bin/openchroot ] ; then
    echo '!'" No executable ~/bin/openchroot.  Can't continue"
    exit 1
fi

#We need to do this in the chroot environment, due to absolute symlinks
#COUNT="`find "$ROOT/root/usr/lib/firefox/defaults/profile/" -type f | wc -l`"

COUNT=`echo "echo -n XXCOUNT= ; find /usr/lib/firefox/browser/defaults/profile/ -type f -not -name '*bak' | wc -l " \
        | ~/bin/openchroot 2>&1 | grep ^XXCOUNT`

[ "$COUNT" = 'XXCOUNT=3' ]

# I don't think we actually need this any more but it's only 1 symlink...
COUNT=`echo "echo -n XXCOUNT= ; find /usr/lib/firefox/defaults/profile/ -type f -not -name '*bak' | wc -l " \
        | ~/bin/openchroot 2>&1 | grep ^XXCOUNT`

[ "$COUNT" = 'XXCOUNT=3' ]
