#!/bin/sh
set -u
set -e

# Check that ufw + gufw is installed and set appropriately
echo
echo "Verifying firewall installation..."

if [ -z "${ROOT:-}" ] ; then
    echo '!'" \$ROOT is not set.  Can't continue"
    exit 1
fi

if [ ! -x ~/bin/openchroot ] ; then
    echo '!'" No executable ~/bin/openchroot.  Can't continue"
    exit 1
fi

# Ensure both are installed
ls "$ROOT"/root/usr/sbin/ufw "$ROOT"/root/usr/bin/gufw

filetocheck="$ROOT"/root/etc/ufw/ufw.conf

if [ ! -e "$filetocheck" ] ; then
    echo '!'" Target file $filetocheck not found.  Can't continue."
    exit 1
fi

if grep -q "^ENABLED=yes" "$filetocheck"; then
    echo ". Seems to be already enabled - good."
    exit 0
fi

echo "~ Enabling and adding rules"

sudo sed -i 's/^ENABLED=no/ENABLED=yes/' "$filetocheck"

~/bin/openchroot <<.
ufw default deny incoming
ufw allow 22
ufw  allow from 127.0.0.0/24 to any port 3306
ufw  allow from 127.0.0.0/24 to any port 5432
.

#Did they stick?
[ "`sudo grep "^-A ufw-user-input" "$ROOT"/root/lib/ufw/user.rules | wc -l`" = 6 ]
