#!/bin/sh
set -u
set -e

# Previously $ROOT/root/etc/resolv.conf symlink was created on boot
# but now it needs to be on the image, and openchroot tinkers with
# it and may not put it back.

echo
echo "Verifying resolv.conf is not AWOL."

if [ -z "${ROOT:-}" ] ; then
    echo '!'" \$ROOT is not set.  Can't continue"
    exit 1
fi

cd "${ROOT}/root/etc"

#Nothing more to do if file is a link
[ ! -L resolv.conf ] || exit 0

echo "~ Adding missing link"
rm -f resolv.conf
ln -s ../run/resolvconf/resolv.conf .
