#!/bin/sh
# Test that /etc contains no bak~ files

if [ -z "${ROOT:-}" ] ; then
    echo '!'" \$ROOT is not set.  Can't continue"
    exit 1
fi

echo
echo "Ensuring that /etc contains no bak~ files"

sudo find ~/reconstructor/root/etc -name '*~' -print -delete | sed 's/^/~ Deleting /'
