#!/bin/sh
set -u
set -e

echo
echo "Verifying that wubi.exe and autorun.inf are gone"

if [ -z "${ROOT:-}" ] ; then
    echo '!'" \$ROOT is not set.  Can't continue"
    exit 1
fi

BAD=0
for f in "$ROOT/remaster/wubi.exe" "$ROOT/remaster/autorun.inf" ; do
    [ -e "$f" ] && echo "! Found $f" && BAD=1
done

[ "$BAD" = 0 ]
