#!/bin/sh
set -u
set -e

# Check that PostgreSQL and MySQL databases are not running.  They will
# be reanabled by biolinuxfirstboot
# Note that MySQL was removed after 8.0.7, so in that respect this is
# redundant but harmless.

echo
echo "Checking PostgreSQL and MySQL will not run on live system"

if [ -z "${ROOT:-}" ] ; then
    echo '!'" \$ROOT is not set.  Can't continue"
    exit 1
fi

ocr="$HOME"/bin/openchroot
if [ ! -x "$ocr" ] ; then
    echo '!'" No executable $ocr.  Can't continue"
    exit 1
fi

crcmd() {
    #Runs a command using openchroot, if you are lucky.
    echo "$*"' | sed "s,^,@@@,"' | $ocr | sed -n '/@@@/s/@@@//p'
}

cd "${ROOT}/root"

# MySQL first.
if [ -e "./var/lib/mysql" ] ; then
    echo "~ Scrubbing MySQL DB"
    sudo rm -rf "./var/lib/mysql"
fi

PGDBS="`crcmd pg_lsclusters | wc -l`"

if [ "$PGDBS" = 0 ] ; then
    echo '!'" No output from pg_lsclusters"
    false
elif [ "$PGDBS" = 1 ] ; then
    echo ". PosgtreSQL has no databases - good."
else
    #See if this works before actually executing it...
    for vers in `crcmd pg_lsclusters | tail -n+2 | awk '{print $1}'` ; do
	echo "pg_dropcluster --stop $vers main" | tee /dev/stderr | $ocr
    done
fi
true
