#!/bin/sh
set -u
set -e

# Check that the console keyboard defaults to gb.  This is a minor thing
# but it annoys me.  See apply_ubiquity_patch for the more serious Gnome
# keyboard fudgings.
echo
echo "Verifying console keyboard settings..."

if [ -z "${ROOT:-}" ] ; then
    echo '!'" \$ROOT is not set.  Can't continue"
    exit 1
fi

if [ ! -x ~/bin/openchroot ] ; then
    echo '!'" No executable ~/bin/openchroot.  Can't continue"
    exit 1
fi


filetocheck="$ROOT"/root/etc/default/keyboard

if [ ! -e "$filetocheck" ] ; then
    echo '!'" Target file $filetocheck not found.  Can't continue."
    exit 1
fi

if grep -q "XKBLAYOUT=.gb." "$filetocheck"; then
    echo ". Seems to be already set - good."
    exit 0
fi

#Note, this gets changed back somehow??
echo "~ Setting layout"
sudo sed -i 's/^XKBLAYOUT=.*/XKBLAYOUT="gb"/' "$filetocheck"

~/bin/openchroot <<.
echo set keyboard-configuration/layout 'English (UK)' | debconf-communicate
echo set keyboard-configuration/variant 'English (UK)' | debconf-communicate
echo set keyboard-configuration/xkb-keymap 'gb' | debconf-communicate
echo set keyboard-configuration/layoutcode 'gb' | debconf-communicate
echo set keyboard-configuration/store_defaults_in_debconf_db true | debconf-communicate
/usr/sbin/update-initramfs -u
.

# I was calling dpkg-reconfigure keyboard-configuration but in a chroot
# this just reverts it to "us" so I think just editing the file and re-diddling
# the initrd is what we need.
if grep -q "^XKBLAYOUT=.gb." "$filetocheck"; then
    echo ". Changes have taken effect - good."
    exit 0
else
    echo '! '"Default keyboard is still not GB. No idea why."
    exit 1
fi
